# Generated by Django 3.1.1 on 2020-11-01 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_list_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='todo_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.todo_list'),
        ),
    ]
